[package]
name = "bls12_381_pairing"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
bignum = {tag = "v0.3.7", git = "https://github.com/noir-lang/noir-bignum"}
noir_bigcurve = {tag = "v0.4", git = "https://github.com/noir-lang/noir_bigcurve"}

